export const Login_Api="https://suitable-jolly-falcon.ngrok-free.app/login" 
export const Signup_api="https://suitable-jolly-falcon.ngrok-free.app/signup"
export const Chat_api='https://suitable-jolly-falcon.ngrok-free.app/chat' 
export const clear_chat_api='https://suitable-jolly-falcon.ngrok-free.app/clear_chat'
export const pdf_upload_api="https://suitable-jolly-falcon.ngrok-free.app/upload"
export const ask_pdf="https://suitable-jolly-falcon.ngrok-free.app/ask_pdf"
export const ask_csv="https://suitable-jolly-falcon.ngrok-free.app/ask_csv"
export const ask_user_details="https://suitable-jolly-falcon.ngrok-free.app/get_subscription"
export const Transcript_api = "https://suitable-jolly-falcon.ngrok-free.app/transcript"
export const Voice_api = "https://suitable-jolly-falcon.ngrok-free.app/voice"